### ISSUE TITLE
Missing dependecy

### ISSUE THREAD

**Issue by nablabits** [pinax/pinax-calendars#13]
Hi there, 
I've just tried the demo, but I've found an error with pip:
`ModuleNotFoundError: No module named 'bootstrapform'`

I've installed `django-bootstrap-form-3.4` and seems to run nice. So it could be added to requirements.txt.

Great app! not for the project I'm currently working on, but valuable in the future.

**Comment by KatherineMichel** [comment]
@nablabits Hello, sorry to have missed this issue a while back. In December, a PR was merged in the pinax-templates installation instructions (referenced in pinax-calendars README) to add guidance for bootstrapform installation. I think this guidance will help you with the problem you had, so I am going to close this issue. Let me know if you need more assistance! https://github.com/pinax/pinax-templates#installation
