### ISSUE TITLE
The date has to be entered manually without any format specified

### ISSUE THREAD

**Issue by shubham7saxena** [pinax/pinax-calendars#6]
some suggestions:
- suggest how the date should be entered in dd/mm/yy or mm/dd/yy or any permutation.
- best solution is to open a small calendar popup to select the date from.

**Comment by ossanna16** [comment]
@jtauber @paltman Any thoughts?

**Comment by shubham7saxena** [comment]
if you find the issue legitimate, I'd be happy to implement and send a a Pull request

**Comment by jtauber** [comment]
@paltman did you say you thought this was a project issue not app?

**Comment by paltman** [comment]
This doesn't really apply to this app as all this app is is a template tag to generate a calendar from a queryset of events.   The [usage is documented](https://github.com/pinax/pinax-calendars#usage) in the README.
