### ISSUE TITLE
Demo app updated to Django 2.0 / latest code?

### ISSUE THREAD

**Issue by WakeRealityDev** [pinax/pinax-calendars#9]
I see there are no commits to the demo app for 2 years. I'm new to pinax and wanted to confirm it works.  Thank you.

**Comment by grahamu** [comment]
Good timing @WakeRealityDev, we just updated the calendars demo app!
Try https://github.com/pinax/pinax-calendars-demo.

**Comment by WakeRealityDev** [comment]
Cool, thank you
